echo "REACT_APP_COGNITO_IDENTITY_POOL_ID=${REACT_APP_COGNITO_IDENTITY_POOL_ID}" >> './.env'
echo "REACT_APP_USER_POOLS_ID=${REACT_APP_USER_POOLS_ID}" >> './.env'
echo "REACT_APP_POOLS_WEB_CLIENT_ID=${REACT_APP_POOLS_WEB_CLIENT_ID}" >> './.env'